name: GitHub CI

on: [push]

jobs:

  security:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: zricethezav/gitleaks-action@master

  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install --frozen-lockfile

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install
      - run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install
      - run: yarn lint
      - run: yarn build
        
      - if: github.ref == 'refs/heads/master'
        name: upload elements artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements
          path:
            packages/elements/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-react artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-react
          path:
            packages/elements-react/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-angular artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-angular
          path:
            packages/elements-angular/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload storybook artifact 
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path:
            packages/storybook/dist/
